secret_key_base: WuQhWwjvzyj6Jwz5tic4T0aIvrwThi52yGdUZDRfC-g
port: 3000
name: noumenomicon

logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: true
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://postgres:@localhost:5432/noumenomicon_development
auto_reload: true

session:
  key: amber.session
  store: signed_cookie
  expires: 0

smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.
